Automated enabling of MPI support
PyORBIT-Collaboration/PyORBIT3 pull request #34
Opened 2024-11-07 15:17 UTC by juanfem

This PR makes meson configure automatically MPI support based on the presence of a valid MPICH installation.

It also includes a `core/__init__.py` file that automatically imports `orbit-mpi` when importing any other module. That initializes MPI and therefore fixes #31.

2024-11-07 16:21 UTC, azukov commented
This looks very nice!
@juanfem  Can you check for openmpi too?

2024-11-07 16:25 UTC, azukov requested changes
check for openmpi if mpich is not available and skip mpi if neither is installed?

2024-11-07 20:35 UTC, juanfem commented
good point, let me check

2024-11-07 20:57 UTC, juanfem commented
done! it seems to work well either way

2024-12-12 20:37 UTC, azukov approved these changes

2024-12-12 20:37 UTC, merged